#ifndef ISP_VULKAN_SHADERS_DEMOSAIC_COMPUTE_H
#define ISP_VULKAN_SHADERS_DEMOSAIC_COMPUTE_H

namespace android {

/* Compute shader consumed by VulkanIspPipeline: reads Bayer bytes out
 * of the input SSBO (binding 0), runs a McGuire / Malvar-He-Cutler 5x5
 * demosaic, applies WB + CCM + sRGB gamma when params.doIsp is set,
 * writes RGBA8 into the scratch storage image (binding 1). The
 * parameter buffer layout (binding 2) mirrors IspParams in
 * isp/IspParams.h — keep the two in sync. */
static const char kDemosaicComputeGlsl[] =
    "#version 450\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(std430, binding = 0) buffer InputBuf  { uint data[]; } inBuf;\n"
    "layout(rgba8, binding = 1) writeonly uniform image2D outImg;\n"
    "layout(std430, binding = 2) buffer Params {\n"
    "    uint width; uint height; uint bayerPhase; uint is16bit;\n"
    "    uint wbR; uint wbG; uint wbB; uint doIsp;\n"
    "    int ccm[9];\n"
    "    uint  blackLevel;\n"
    "    float denomRecip255;\n"
    "    uint  gammaLut[256];\n"
    "} params;\n"
    "layout(std430, binding = 4) buffer Stats {\n"
    "    uint lumaHist  [128];\n"
    "    uint rgbSum    [768];   /* 16*16*3 flat, Q16.16 fixed */\n"
    "    uint sharpSum  [256];   /* 16*16,     Q24.8  fixed   */\n"
    "} stats;\n"
    "/* Subtract the sensor's optical-black bias and rescale to a full\n"
    " * 0..255 range so highlights aren't compressed. blackLevel==0\n"
    " * and denomRecip255 = 255/maxRaw are selected on the host so the\n"
    " * shader keeps one multiply in the hot path instead of a runtime\n"
    " * integer divide (emulated on Kepler, ~20-30 cycles each). */\n"
    "float readPixel(uint x, uint y) {\n"
    "    uint raw;\n"
    "    if (params.is16bit != 0u) {\n"
    "        uint idx = y * params.width + x;\n"
    "        uint word = inBuf.data[idx >> 1u];\n"
    "        raw = ((idx & 1u) == 0u) ? (word & 0xFFFFu) : (word >> 16);\n"
    "    } else {\n"
    "        uint idx = y * params.width + x;\n"
    "        uint word = inBuf.data[idx >> 2u];\n"
    "        raw = (word >> ((idx & 3u) * 8u)) & 0xFFu;\n"
    "    }\n"
    "    return max(float(raw) - float(params.blackLevel), 0.0) * params.denomRecip255;\n"
    "}\n"
    "/* Cooperative Bayer tile: every 16x16 workgroup owns a 16x16 block\n"
    " * of output pixels plus a 2-pixel halo on each side = 20x20\n"
    " * samples. The 256 threads load ~1.56 samples each into shared\n"
    " * memory; the Malvar-He-Cutler kernel then reads PX(dx,dy) from\n"
    " * shared instead of issuing 13 SSBO reads per output pixel. On\n"
    " * GK20A the SSBO chases two rows above / below the centre had\n"
    " * cold L2 behaviour under preview load — the tile wipes that out\n"
    " * and folds the P1(a) per-sample divide into a single call per\n"
    " * loaded pixel rather than thirteen. 16x16 amortises the halo\n"
    " * across more output pixels than 8x8 and lifts SMX occupancy\n"
    " * from ~50 %% to ~75 %% on Kepler's 16-blocks-per-SM limit. */\n"
    "shared float tile[20][20];\n"
    "shared float wgLuma[16][16];\n"
    "shared vec4  sReduce[256];\n"
    "shared uint  sHist[8][128];\n"
    "void main() {\n"
    "    uint lx = gl_LocalInvocationID.x;\n"
    "    uint ly = gl_LocalInvocationID.y;\n"
    "    uint tid = ly * 16u + lx;\n"
    "    int wgOrigX = int(gl_WorkGroupID.x * 16u);\n"
    "    int wgOrigY = int(gl_WorkGroupID.y * 16u);\n"
    "    int iw = int(params.width) - 1;\n"
    "    int ih = int(params.height) - 1;\n"
    "\n"
    "    /* Cooperative halo load — 400 samples, 256 threads, up to two\n"
    "     * iterations per thread. Out-of-image halo clamps to the nearest\n"
    "     * edge so downstream PX() reads behave as if the image were\n"
    "     * extended with edge replication. */\n"
    "    for (uint i = tid; i < 400u; i += 256u) {\n"
    "        uint tx = i % 20u;\n"
    "        uint ty = i / 20u;\n"
    "        int gx = clamp(wgOrigX + int(tx) - 2, 0, iw);\n"
    "        int gy = clamp(wgOrigY + int(ty) - 2, 0, ih);\n"
    "        tile[ty][tx] = readPixel(uint(gx), uint(gy));\n"
    "    }\n"
    "    /* Zero per-warp histogram bands — 1024 uints / 256 threads = 4\n"
    "     * writes per thread. Shares the tile-load barrier. */\n"
    "    for (uint i = tid; i < 1024u; i += 256u) {\n"
    "        sHist[i / 128u][i % 128u] = 0u;\n"
    "    }\n"
    "    barrier();\n"
    "\n"
    "    uint x = gl_GlobalInvocationID.x;\n"
    "    uint y = gl_GlobalInvocationID.y;\n"
    "    bool inBounds = (x < params.width) && (y < params.height);\n"
    "\n"
    "    /* McGuire/Malvar-He-Cutler 5x5 demosaic - 13 samples, branch-free.\n"
    "     * Run for every thread (not just in-bounds): the cooperative tile\n"
    "     * load clamped halo samples to the image edge, so out-of-bounds\n"
    "     * threads compute on replicated data — safe, and lets us skip a\n"
    "     * divergent early return that would break the upcoming barrier. */\n"
    "#define PX(dx, dy) tile[int(ly) + 2 + (dy)][int(lx) + 2 + (dx)]\n"
    "    float pC  = PX(0, 0);\n"
    "    float pN  = PX(0,-1);  float pS  = PX(0, 1);\n"
    "    float pW  = PX(-1, 0); float pE  = PX(1, 0);\n"
    "    float pN2 = PX(0,-2);  float pS2 = PX(0, 2);\n"
    "    float pW2 = PX(-2, 0); float pE2 = PX(2, 0);\n"
    "    float pNW = PX(-1,-1); float pNE = PX(1,-1);\n"
    "    float pSW = PX(-1, 1); float pSE = PX(1, 1);\n"
    "#undef PX\n"
    "    float vFar  = pN2 + pS2;\n"
    "    float vNear = pN + pS;\n"
    "    float diag  = pNW + pNE + pSW + pSE;\n"
    "    float hFar  = pW2 + pE2;\n"
    "    float hNear = pW + pE;\n"
    "\n"
    "    float Pcross = (4.0*pC - vFar + 2.0*vNear - hFar + 2.0*hNear) * 0.125;\n"
    "    float Pcheck = (6.0*pC - 1.5*vFar + 2.0*diag - 1.5*hFar) * 0.125;\n"
    "    float Ptheta = (5.0*pC + 0.5*vFar - diag - hFar + 4.0*hNear) * 0.125;\n"
    "    float Pphi   = (5.0*pC - vFar - diag + 0.5*hFar + 4.0*vNear) * 0.125;\n"
    "\n"
    "    /* Branch-free Bayer position selection */\n"
    "    uint rX = params.bayerPhase & 1u;\n"
    "    uint rY = (params.bayerPhase >> 1) & 1u;\n"
    "    bool isRedRow = ((y + rY) & 1u) == 0u;\n"
    "    bool isRedCol = ((x + rX) & 1u) == 0u;\n"
    "    float fR = isRedRow ? (isRedCol ? pC : Ptheta) : (isRedCol ? Pphi : Pcheck);\n"
    "    float fG = (isRedRow == isRedCol) ? Pcross : pC;\n"
    "    float fB = isRedRow ? (isRedCol ? Pcheck : Pphi) : (isRedCol ? Ptheta : pC);\n"
    "    int R = clamp(int(fR + 0.5), 0, 255);\n"
    "    int G = clamp(int(fG + 0.5), 0, 255);\n"
    "    int B = clamp(int(fB + 0.5), 0, 255);\n"
    "\n"
    "    if (params.doIsp != 0u) {\n"
    "        R = clamp((R * int(params.wbR)) >> 8, 0, 255);\n"
    "        G = clamp((G * int(params.wbG)) >> 8, 0, 255);\n"
    "        B = clamp((B * int(params.wbB)) >> 8, 0, 255);\n"
    "        int rr = clamp((params.ccm[0]*R + params.ccm[1]*G + params.ccm[2]*B) >> 10, 0, 255);\n"
    "        int gg = clamp((params.ccm[3]*R + params.ccm[4]*G + params.ccm[5]*B) >> 10, 0, 255);\n"
    "        int bb = clamp((params.ccm[6]*R + params.ccm[7]*G + params.ccm[8]*B) >> 10, 0, 255);\n"
    "        R = int(params.gammaLut[rr]);\n"
    "        G = int(params.gammaLut[gg]);\n"
    "        B = int(params.gammaLut[bb]);\n"
    "    }\n"
    "\n"
    "    /* Per-thread luma into shared memory. Every thread writes\n"
    "     * (0 for out-of-bounds so the Sobel readers in the next\n"
    "     * commit don't sample uninitialised slots), then one barrier\n"
    "     * makes the 16x16 block visible to its neighbours. Not read\n"
    "     * in this commit — this measures the bare cost of the write\n"
    "     * + barrier on PERF-GPU before any consumer lands. */\n"
    "    /* Luma computed once per thread, used for both the per-WG\n"
    "     * tile (Sobel readers) and the per-warp histogram privatized\n"
    "     * band below. Out-of-bounds threads write 0 so the barrier\n"
    "     * remains uniform; only in-bounds threads contribute to the\n"
    "     * histogram. */\n"
    "    float myLuma = inBounds\n"
    "        ? (float(R) * 0.299 + float(G) * 0.587 + float(B) * 0.114) * (1.0 / 255.0)\n"
    "        : 0.0;\n"
    "    wgLuma[ly][lx] = myLuma;\n"
    "    if (inBounds) {\n"
    "        uint warpId = tid >> 5u;   /* 0..7 */\n"
    "        uint bin = uint(clamp(myLuma * 128.0, 0.0, 127.0));\n"
    "        atomicAdd(sHist[warpId][bin], 1u);\n"
    "    }\n"
    "    barrier();\n"
    "\n"
    "    if (inBounds) {\n"
    "        imageStore(outImg, ivec2(int(x), int(y)),\n"
    "                   vec4(float(R), float(G), float(B), 255.0) / 255.0);\n"
    "    }\n"
    "\n"
    "    /* Per-WG accumulator packed as vec4(R, G, B, sharpness).\n"
    "     * Inner 14x14 threads add their Sobel Tenengrad into the w\n"
    "     * channel; edge threads leave w = 0 because their 3x3 Sobel\n"
    "     * neighbourhood sits outside the wgLuma tile. All 256 threads\n"
    "     * feed the xyz channels with the post-ISP RGB scaled by 1/255.\n"
    "     * One log2(256) tree reduce collapses the four partials\n"
    "     * simultaneously — replaces five separate per-channel\n"
    "     * reductions (Sobel + R + G + B + count) that cost ~13 ms in\n"
    "     * aggregate from barrier and shared-mem overhead. */\n"
    "    float mySharp = 0.0;\n"
    "    if (inBounds && ly >= 1u && ly <= 14u && lx >= 1u && lx <= 14u) {\n"
    "        float tl = wgLuma[ly - 1u][lx - 1u];\n"
    "        float t  = wgLuma[ly - 1u][lx     ];\n"
    "        float tr = wgLuma[ly - 1u][lx + 1u];\n"
    "        float l  = wgLuma[ly     ][lx - 1u];\n"
    "        float r  = wgLuma[ly     ][lx + 1u];\n"
    "        float bl = wgLuma[ly + 1u][lx - 1u];\n"
    "        float b  = wgLuma[ly + 1u][lx     ];\n"
    "        float br = wgLuma[ly + 1u][lx + 1u];\n"
    "        float Gx = (tr + 2.0 * r + br) - (tl + 2.0 * l + bl);\n"
    "        float Gy = (bl + 2.0 * b + br) - (tl + 2.0 * t + tr);\n"
    "        mySharp = Gx * Gx + Gy * Gy;\n"
    "    }\n"
    "\n"
    "    /* Flush the 8 per-warp histogram bands into the global\n"
    "     * histogram — done before the vec4 reduction so the 128\n"
    "     * flushing threads retire before sReduce is clobbered. */\n"
    "    if (tid < 128u) {\n"
    "        uint sum = 0u;\n"
    "        for (uint w = 0u; w < 8u; w++) {\n"
    "            sum += sHist[w][tid];\n"
    "        }\n"
    "        atomicAdd(stats.lumaHist[tid], sum);\n"
    "    }\n"
    "\n"
    "    vec4 myAccum = inBounds\n"
    "        ? vec4(float(R), float(G), float(B), 0.0) * vec4(1.0 / 255.0, 1.0 / 255.0, 1.0 / 255.0, 0.0)\n"
    "          + vec4(0.0, 0.0, 0.0, mySharp)\n"
    "        : vec4(0.0);\n"
    "    sReduce[tid] = myAccum;\n"
    "    barrier();\n"
    "    for (uint s = 128u; s > 0u; s >>= 1u) {\n"
    "        if (tid < s) sReduce[tid] += sReduce[tid + s];\n"
    "        barrier();\n"
    "    }\n"
    "    if (tid == 0u) {\n"
    "        uint wgCenterX = gl_WorkGroupID.x * 16u + 8u;\n"
    "        uint wgCenterY = gl_WorkGroupID.y * 16u + 8u;\n"
    "        uint patchX = min(wgCenterX * 16u / params.width, 15u);\n"
    "        uint patchY = min(wgCenterY * 16u / params.height, 15u);\n"
    "        uint patchIdx = patchY * 16u + patchX;\n"
    "        vec4 total = sReduce[0];\n"
    "        atomicAdd(stats.rgbSum[patchIdx * 3u + 0u], uint(total.x * 65536.0));\n"
    "        atomicAdd(stats.rgbSum[patchIdx * 3u + 1u], uint(total.y * 65536.0));\n"
    "        atomicAdd(stats.rgbSum[patchIdx * 3u + 2u], uint(total.z * 65536.0));\n"
    "        atomicAdd(stats.sharpSum[patchIdx],         uint(total.w * 256.0));\n"
    "    }\n"
    "}\n";

}; /* namespace android */

#endif /* ISP_VULKAN_SHADERS_DEMOSAIC_COMPUTE_H */
